version: "3"
services:
    db-template:
        image: postgres
        container_name: db-template
        restart: always

        volumes:
            - psql-template:/var/lib/postgresql/data-template

        ports:
            - 5432:5432

        environment:
            - POSTGRES_DB=atlas
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    pgadmin-template:
        image: dpage/pgadmin4
        container_name: pgadmin-template
        restart: always

        volumes:
            - pgad-template:/var/lib/pgadmin-template

        ports:
            - "5050:80"

        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
volumes:
    psql-template:
    pgad-template:
